# Generated by Django 5.0.7 on 2024-11-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assunto',
            options={'ordering': ['materia', 'nome'], 'verbose_name': 'Assunto', 'verbose_name_plural': 'Assuntos'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'ordering': ['materia', 'assunto', '-data_criacao'], 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='created_at',
            new_name='data_criacao',
        ),
        migrations.AlterUniqueTogether(
            name='assunto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='respostausuario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='materia',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='assunto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_e',
            field=models.CharField(default='Sem resposta', max_length=500),
        ),
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')], default=1),
        ),
        migrations.AlterField(
            model_name='respostausuario',
            name='correta',
            field=models.BooleanField(editable=False),
        ),
        migrations.RemoveField(
            model_name='assunto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assunto',
            name='updated_at',
        ),
    ]
