# Generated by Django 5.0.7 on 2024-11-08 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_assunto_options_alter_questao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'ordering': ['materia', 'assunto', '-id'], 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterUniqueTogether(
            name='assunto',
            unique_together={('nome', 'materia')},
        ),
        migrations.RemoveField(
            model_name='materia',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_e',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='respostausuario',
            unique_together={('usuario', 'questao')},
        ),
        migrations.RemoveField(
            model_name='assunto',
            name='descricao',
        ),
    ]
