# Generated by Django 5.0.7 on 2024-11-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_questao_options_alter_assunto_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='url_imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
