# Generated by Django 5.0.7 on 2024-11-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_achievementtype_userachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementtype',
            name='requirement_type',
            field=models.CharField(choices=[('total_correct', 'Total de respostas corretas'), ('subject_correct', 'Assuntos'), ('topic_correct', 'Tópicps'), ('streak', 'Sequência de respostas')], max_length=50),
        ),
    ]
