# Generated by Django 5.0.7 on 2024-11-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_achievementtype_requirement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementtype',
            name='requirement_type',
            field=models.CharField(choices=[('total_correct', 'Total de respostas corretas'), ('subject_correct', 'Respostas corretas por matéria'), ('topic_correct', 'Respostas corretas por tópico'), ('streak', 'Sequência de respostas corretas')], max_length=50),
        ),
    ]
