# Generated by Django 5.0.7 on 2024-11-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_achievementtype_requirement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementtype',
            name='icon',
        ),
        migrations.AddField(
            model_name='achievementtype',
            name='icon_url',
            field=models.CharField(default='https://cdn.lordicon.com/zfzufhzk.json', help_text='Ex: https://cdn.lordicon.com/zfzufhzk.json', max_length=255, verbose_name='URL do Lordicon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='requirement_type',
            field=models.CharField(choices=[('total_correct', 'Total de respostas corretas'), ('subject_correct', 'Respostas corretas por matéria'), ('topic_correct', 'Respostas corretas por tópico'), ('streak', 'Sequência de respostas corretas')], max_length=50, verbose_name='Tipo de Requisito'),
        ),
    ]
