# Generated by Django 5.0.7 on 2024-11-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_achievementtype_icon_achievementtype_icon_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementtype',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='achievementtype',
            name='icon',
            field=models.CharField(default='bi bi-book', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='requirement_type',
            field=models.CharField(choices=[('total_correct', 'Total de respostas corretas'), ('subject_correct', 'Respostas corretas por matéria'), ('topic_correct', 'Respostas corretas por tópico'), ('streak', 'Sequência de respostas corretas')], max_length=50),
        ),
    ]
