# Generated by Django 5.0.7 on 2024-11-13 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_achievementtype_icon_url_achievementtype_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementtype',
            options={'verbose_name': 'Tipo de Conquista', 'verbose_name_plural': 'Tipos de Conquistas'},
        ),
        migrations.RemoveField(
            model_name='achievementtype',
            name='icon',
        ),
        migrations.AddField(
            model_name='achievementtype',
            name='icon_url',
            field=models.CharField(default='https://cdn.lordicon.com/zfzufhzk.json', help_text='URL do ícone do Bootstrap (ex: bi bi-trophy-fill)', max_length=255, verbose_name='URL do Ícone'),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='requirement_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.materia', verbose_name='Matéria Requerida'),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='requirement_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.assunto', verbose_name='Tópico Requerido'),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='requirement_type',
            field=models.CharField(choices=[('total_correct', 'Total de respostas corretas'), ('subject_correct', 'Respostas corretas por matéria'), ('topic_correct', 'Respostas corretas por tópico'), ('streak', 'Sequência de respostas corretas')], max_length=50, verbose_name='Tipo de Requisito'),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='requirement_value',
            field=models.IntegerField(verbose_name='Valor do Requisito'),
        ),
    ]
