# Generated by Django 5.0.7 on 2024-11-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_achievementtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementtype',
            name='icon_url',
            field=models.CharField(default='bi bi-trophy-fill', help_text='Classe do ícone do Bootstrap (ex: bi bi-trophy-fill, bi bi-star-fill)', max_length=50, verbose_name='Classe do Ícone'),
        ),
    ]
