# Generated by Django 5.0.7 on 2024-11-08 09:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activation_token',
            field=models.UUIDField(default=accounts.models.generate_activation_token, editable=False),
        ),
    ]
